[#ftl]
[@b.head/]
[@b.toolbar title="转专业申请设置"/]
	[@b.form name="transferSchemeEditForm" action=b.rest.save(transferScheme) theme="list"]
	  [@b.field label="学年学期"]${transferScheme.semester.schoolYear}学年度${transferScheme.semester.name}学期[/@]
    [@b.textfield label="名称" name="transferScheme.name" value=transferScheme.name maxlength="100"/]
    [@b.startend label="院系制定计划" name="transferScheme.editBeginAt,transferScheme.editEndAt" format="yyyy-MM-dd HH:mm:ss" start=transferScheme.editBeginAt! end=transferScheme.editEndAt! required="true"/]
    [@b.startend label="学生提交申请" name="transferScheme.applyBeginAt,transferScheme.applyEndAt" format="yyyy-MM-dd HH:mm:ss" start=transferScheme.applyBeginAt! end=transferScheme.applyEndAt! required="true"/]
    [@b.startend label="院系面试审核" name="transferScheme.auditBeginAt,transferScheme.auditEndAt" format="yyyy-MM-dd HH:mm:ss" start=transferScheme.auditBeginAt! end=transferScheme.auditEndAt! required="true"/]
    [@b.radios label="是否发布" name="transferScheme.published" value=transferScheme.published/]
    [@b.formfoot]
      [@b.submit value="保存"/]
    [/@]
  [/@]
[@b.foot/]